sudo: required
language: bash

before_install:
        - sudo apt-get update
        - sudo apt-get install shellcheck
        - sudo apt-get install imagemagick 

        - wget "https://c4pr1c3.github.io/LinuxSysAdmin/exp/chap0x04/worldcupplayerinfo.tsv"
        - wget "https://c4pr1c3.github.io/LinuxSysAdmin/exp/chap0x04/web_log.tsv.7z"

        - sudo apt install p7zip-full
        - 7z x web_log.tsv.7z

script:


         #任务一:用bash编写一个图片批处理脚本

         - bash  -h  
         - bash shell_script/image_process.sh -q 80 ./Image
         - bash shell_script/image_process.sh -r 50 ./Image
         - bash shell_script/image_process.sh -w watermark ./Image
         - bash shell_script/image_process.sh -p 0 head ./Image
         - bash shell_script/image_process.sh -p 1 tail ./Image
         - bash shell_script/image_process.sh -t ./Image

          
         #任务二：用bash编写一个文本批处理脚本
         #worldcupplayer

         - bash shell_script/worldcupplayer.sh -h
         - bash shell_script/worldcupplayer.sh -a
         - bash shell_script/worldcupplayer.sh -b
         - bash shell_script/worldcupplayer.sh -c
         - bash shell_script/worldcupplayer.sh -d
          

         #web_log

         - bash shell_script/webserver.sh -h
         - bash shell_script/webserver.sh -a
         - bash shell_script/webserver.sh -b
         - bash shell_script/webserver.sh -c
         - bash shell_script/webserver.sh -d
         - bash shell_script/webserver.sh -e
         - bash shell_script/webserver.sh -f /ksc.html


notifications:
          email:
                  on_success: never
